name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out=tfplan

      # Save plan to artifacts  
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
            name: tfplan
            path: ./terraform-test/tfplan

    #   - name: Show Terraform Plan (human-readable)
    #     run: terraform show -no-color tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    environment: production  # Triggers approval before apply
    needs: terraform-plan
    defaults:
        run:
            working-directory: ./terraform-test

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

    # Download saved plan from artifacts  
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
            name: tfplan
            path: ./terraform-test/tfplan

    # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan/tfplan